In [2]:
import pandas

In [5]:
data = pandas.read_csv("MetObjects.csv")

/tmp/ipykernel_29/1229616624.py:1: DtypeWarning: Columns (5,7,10,11,12,13,14,34,35,36,37,38,39,40,41,42,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pandas.read_csv("MetObjects.csv")

In [8]:
data.columns

Index(['Object Number', 'Is Highlight', 'Is Timeline Work', 'Is Public Domain',
       'Object ID', 'Gallery Number', 'Department', 'AccessionYear',
       'Object Name', 'Title', 'Culture', 'Period', 'Dynasty', 'Reign',
       'Portfolio', 'Constituent ID', 'Artist Role', 'Artist Prefix',
       'Artist Display Name', 'Artist Display Bio', 'Artist Suffix',
       'Artist Alpha Sort', 'Artist Nationality', 'Artist Begin Date',
       'Artist End Date', 'Artist Gender', 'Artist ULAN URL',
       'Artist Wikidata URL', 'Object Date', 'Object Begin Date',
       'Object End Date', 'Medium', 'Dimensions', 'Credit Line',
       'Geography Type', 'City', 'State', 'County', 'Country', 'Region',
       'Subregion', 'Locale', 'Locus', 'Excavation', 'River', 'Classification',
       'Rights and Reproduction', 'Link Resource', 'Object Wikidata URL',
       'Metadata Date', 'Repository', 'Tags', 'Tags AAT URL',
       'Tags Wikidata URL'],
      dtype='object')

In [12]:
data = data.drop(columns = ['Object Number', 'Is Highlight', 'Is Timeline Work', 'Is Public Domain',
       'Object ID', 'Gallery Number', 'Title', 'Dynasty', 'Reign','Portfolio', 'Constituent ID', 'Artist Role', 'Artist Prefix',
       'Artist Display Name', 'Artist Display Bio', 'Artist Suffix',
       'Artist Alpha Sort', 'Artist Begin Date','Artist End Date', 'Artist ULAN URL',
       'Artist Wikidata URL', 'Object Begin Date',
       'Object End Date', 'Dimensions', 'Credit Line',
       'City', 'State', 'County',
       'Subregion', 'Locale', 'Locus', 'Excavation', 'River', 'Classification',
       'Rights and Reproduction', 'Link Resource', 'Object Wikidata URL',
       'Metadata Date', 'Repository', 'Tags', 'Tags AAT URL',
       'Tags Wikidata URL'])
data

,Department,AccessionYear,Object Name,Culture,Period,Artist Nationality,Artist Gender,Object Date,Medium,Geography Type,Country,Region
0,The American Wing,1979.0,Coin,NaN,NaN,American,NaN,1853,Gold,NaN,NaN,NaN
1,The American Wing,1980.0,Coin,NaN,NaN,,NaN,1901,Gold,NaN,NaN,NaN
2,The American Wing,1967.0,Coin,NaN,NaN,NaN,NaN,1909–27,Gold,NaN,NaN,NaN
3,The American Wing,1967.0,Coin,NaN,NaN,NaN,NaN,1909–27,Gold,NaN,NaN,NaN
4,The American Wing,1967.0,Coin,NaN,NaN,NaN,NaN,1909–27,Gold,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
477799,Drawings and Prints,1923,Drawing,NaN,NaN,,NaN,1904,"Graphite on cardstock adhered to canvas, perfo...",NaN,NaN,NaN
477800,Drawings and Prints,1923,Drawing,NaN,NaN,,NaN,1904,Graphite and ink,NaN,NaN,NaN
477801,Drawings and Prints,1953,Print,NaN,NaN,,NaN,after 1773,Etching,NaN,NaN,NaN
477802,Drawings and Prints,1923,Drawing,NaN,NaN,,NaN,1904,Graphite,NaN,NaN,NaN
477803,Drawings and Prints,1923,Drawing,NaN,NaN,,NaN,1904,ink,NaN,NaN,NaN

In [51]:
nationality = data.columns[data.isnull().mean()==0]
nationality

Index(['Department', 'Artist Nationality'], dtype='object')

In [15]:
data.isna().sum()

Department                 0
AccessionYear           3556
Object Name             1691
Culture               270425
Period                386848
Artist Nationality    202269
Artist Gender         374743
Object Date            13867
Medium                  7120
Geography Type        418035
Country               402053
Region                446444
dtype: int64

In [35]:
nationality = data.dropna(subset = ["Artist Nationality"])
nationality = nationality[(nationality["Artist Nationality"] != " ")]
nationality = nationality[(nationality["Artist Nationality"] != " | ")]
nationality = nationality[(nationality["Artist Nationality"] != " | | ")]
nationality = nationality[(nationality["Artist Nationality"] != " | | | ")]
nationality = nationality[(nationality["Artist Nationality"] != " | | | | ")]
nationality = nationality[(nationality["Artist Nationality"] != " | | | | | ")]
nationality = nationality[(nationality["Artist Nationality"] != " | | | | | | ")]
nationality

,Department,AccessionYear,Object Name,Culture,Period,Artist Nationality,Artist Gender,Object Date,Medium,Geography Type,Country,Region
0,The American Wing,1979.0,Coin,NaN,NaN,American,NaN,1853,Gold,NaN,NaN,NaN
11,The American Wing,1979.0,Coin,NaN,NaN,American,NaN,1876,Gold,NaN,NaN,NaN
32,The American Wing,1964.0,Bust,American,NaN,American,NaN,1876,Pressed glass,Made in,United States,NaN
36,The American Wing,1938.0,Figure,British (American market),NaN,French,NaN,ca. 1785,"Earthenware, basalt",Made in,England,NaN
37,The American Wing,1938.0,Figure,British (American market),NaN,French,NaN,ca. 1785,"Earthenware, basalt",Made in,England,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
477664,Drawings and Prints,1954,Book; prints,NaN,NaN,| | | | | | |,|||||||,1761,Etching and engraving,NaN,NaN,NaN
477691,Drawings and Prints,1883,Print,NaN,NaN,| | | | | | |,|||||||,ca. 1762,Etching and engraving,NaN,NaN,NaN
477733,Drawings and Prints,1951,Print,NaN,NaN,| | | | | |,||||||,1743,Engraving,NaN,NaN,NaN
477740,Drawings and Prints,1951,Print,NaN,NaN,| | | | | | |,|||||||,"February 16, 1750",Etching and engraving,NaN,NaN,NaN
477742,Drawings and Prints,1951,Print,NaN,NaN,| | | | | |,||||||,1743,Etching and engraving,NaN,NaN,NaN

In [43]:
a = nationality["Artist Gender"].unique()
for x in range(len(a)):
    print(a[x])

nan
|
|Female
||
||||
Female|
Female
|||
Female|Female
||Female
|Female|Female
Female||
Female|Female|Female|Female|Female||Female|Female||||||Female|Female|Female|Female|||Female|||Female|Female|
|Female|
|||Female
Female||Female
Female|Female|Female|
||||||||
|||||||||||||||||||||||||||
Female|Female|
Female|Female||
Female|||
|Female||
|Female||Female
||Female|
Female|Female|Female
||||||
|Female|||Female
|||||
||||Female|
||||||||||
||||||||||||||||
|||||||
|||||||||||||
|||||||||
||||||||||||||||||||
Female|||||||||||||||||||||||||||||Female||Female||||
Female||||Female|||Female|||||||||||||||||Female|
|Female||||||||||||||Female
||||||Female||||||
Female||||Female|||||Female|||
||||Female||||||Female|||||Female||||Female
||||Female
||||||||||||||||||||||||||||||
||Female||
Female|||||||Female|Female||||Female||
|||||||||||||||||
||||||||||||||||||
||Female|Female|Female|||||Female|||||
||||||||||||
|||||||||||||||
||||||||||||||||||||||||||||||||||||||
||Female||||||
||||||||||||||||||||||||||
Female|||Female|
|||||||||||
||Female|||||||||||Female|||||||
|||||||||Female
||||||||Female||||||||
|Female||||||||||||||Female||||
|||Female|
|||||||||||||Female||||||
|||||||||||||||||||||||||||||
|||||||Female|Female
|||||||Female|
||||||||||||||Female|||||||
||||||||||||||
|||||||||Female|
||Female||Female||
|Female|Female|Female
|Female||||||||||||||||Female|||||||||||||||
|||||Female||||||||||||Female|||Female|||||||||
||||||||||||Female|||||Female||||||||||||||
|||||||||||||||||Female||||||||||||||||
|Female|||||||||||||||||||||||
|||||||||||||||||||||||||||||||||||||Female|||||||||||||||||||||||||
|Female||||||||||||||||||||||||||Female||||Female|||||||||||||||||
||||||||||||||||Female|||||||||||||
Female|||||Female|
||||||||||||||||||||Female||Female||||Female|Female|Female|||||||Female|||Female|Female|||||||||||||Female|||||||||||||||Female
Female||||||||||||
||||||||||||||||||||||||||||||||
|||||||||||||||||||||||||
|||||Female|||||||
|||||||||||||||||||||||||||||||||
|||||Female||
|||Female|||||
|||||Female
||||||||||||||||||||||||
|||||||Female|||||||||||||||||||||||||
|||||||||||||||||||||||||||||||||||||
|||||||||||||||||||
|||||Female||||Female|
||||||||Female|Female|Female|||||||||||||Female|||||
|||||||||Female|||||||||||||||||||||||
|||Female||
|||||||||||||||||||||||||||||||||||||||||||||||||
||||||||Female||||
||||||||||||||||||||||
|||||||||||||||||||||||||||||||||||||||||||||||
Female||||
||||||||||||Female|||||
|Female||||||||
||||||||||||Female||||Female||||Female|||||||||||
||Female||||
|||||||||||||||||||||||||||||||||||
||||Female|||
Female||Female|Female
Female|Female||Female
||||||||Female|
|Female|Female|||Female
||||||Female
||||||||||||||||||||||||||||
|||Female|||
||Female|Female|Female|||||||Female||
|||||||||||||||||Female|||||
||||Female|||||||
||||||||||||||||||||||||||||||Female|||||
|||||||||||||||||||||Female||||||||||||||||||||
|||||||||||||||||||||
||||||||||||||||||||||||||Female|
||Female|||
||||||Female||
|||Female||Female|
||||||||||||||Female|||||Female||
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
|||||||Female
|||||||||||||||||||||||||||||||||||||||||
||||||||Female|||||||
|||Female|||Female|Female||||||Female|||||||||||||||||
||||||||||||||||||||Female|||||||||||||
|||||||||||||||||||||||||||||||||||||||
|||||Female|
Female||||||
||||||||||||||Female|||||
|||||Female||||||
|Female|||||
||||Female|Female||||Female||||||||Female|||
|||||||||||||Female|||
||||||Female|||||
||Female||||||Female||||||||
||||||||||||||||||||||||||||||||||||||||||||||||||
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
||Female||||Female|Female
|||||||||||||||Female||||
|||||||||||||||Female||Female||||||||Female||||
|Female|||
Female||Female||Female|||||||||||||
Female|||||||
Female|||Female||||||||||Female|||||
Female||Female||||||Female|
|||||Female|Female||||
||||Female||||||||
|||||Female||||||||||||
||||||||||||||||||||||||||||||||||Female||||||||||Female
||||||||||||Female||||
||||||||||Female||
||||Female||
|Female||||||||Female|||||||Female|||||||||Female||||
||||Female|||||||||||
||||||||||||||||||||||||||||||Female|Female||||||||||||||||||||||||||||||||||||||||||Female||||Female|||||||||Female|Female|||||||||||||||||Female||Female||||||||||||||||||||||||||||
||||||||||||||||Female||||||
|Female||||
|||||Female|||||||||||||Female||||||||||||||||||||||||||
||||||||Female||||||||||||||||||||
Female|||||
||||||||Female|||||Female||||||||||||Female||Female|Female|||||||||||||||Female|||||||
|||Female||||||||||||||||
|||Female|||||Female
||Female|||Female|||
|Female|||||||||Female|
|||Female||||||Female|||||||Female||||
Female|||||Female||||||||||||||||Female|
||Female|Female||||Female|Female|||||||||Female|
||Female|Female||||||Female||Female||||
|||||||||||||||Female|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||Female||||||||
|||Female||||||||
|||||||||Female|||||
|||||||Female|||||||
||Female|Female||
||||Female||Female||||Female|||||
|||||||||||||||||||||||
|||||||||||Female||||||||||Female||||||
||||||||||||||||||||Female||
||||||||||||||||||Female||
|Female|||||||||||Female||||||
||Female||Female|Female||Female|Female||||Female||Female|Female||Female||Female|||
Female||||Female||||||Female||||Female||Female|||||Female||||||Female|Female|||Female|Female
||||Female|||||
|||Female|||||||||||Female||||||||
|||||||||||||||Female|||
|||Female|||Female|||
||||||||||||||||||||||||||||||||||||||||||||
||||||||||||||Female|||||||||||||||||||||||
|Female|Female||
Female||||||Female
||||||Female|||
||Female||||||||
||Female|||||
||||||||||Female|||||||Female|||||||||||||
||||||||||||Female|||||||||
||||||||||||||||Female||||||||||
||||||||||||||||||||||||||||||Female||||||||||||||Female|||
||||||||||||Female||||||||Female||
|Female||||Female|Female||||||
|||||||||||||Female|||||||Female||
||||||||||||Female|||Female||
|Female||Female||||Female|Female|Female|Female|Female|Female|Female|Female|
||||||||||||Female|||||||||||Female||Female|Female||||||||||||Female||
|||||||||||||||||||||||||||||||||||||||||||
Female|Female||Female|
Female||||||||||||||Female|||||||||||||||||
||Female|||||||
Female|||Female|||Female|
|Female||||||||||||||||||||||||||||
|Female|||||||
|||||Female||||||||||||||
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Female||||Female|||Female|Female|Female|Female||||||Female||Female||Female|Female|||Female||Female|Female||Female|Female|Female||||Female||||
|||||||||Female||||||||
|||||||||||||||||Female
||Female|||||||||
Female|Female|||
||||||Female|||||||||||||||||||Female|||||||||
|||||||Female|||||||||||||||
||||||||||||||||||||||||||||||||||||||||||||||||||||||||Female||||||||||||||||Female|||||||||||||||||||||||||||||||||||
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||Female|||||||||||||Female|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
|||||||||||||||||||||||||||||||Female||||||||
|Female||Female|Female|||||
|||||||||||||||||||||||||Female||||
|||||||||||||||||||||Female||||||
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Female|||||||||||
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||Female
Female||||Female
Female|||Female
Female||||Female|
|Female|Female|
|||||||||||||||||Female||Female|||
||Female||||||||||||||||||||||||
|||||||||||||Female||||||||||||
Female||||||||||||||
Female|||||||||||||
Female|||||Female
||||||||||||||Female||Female|||||||
|||||Female||||
||||||||||||||||||||Female||||||
||Female|Female|
Female||Female|Female|Female||Female|Female||
Female|Female|Female|Female|Female|Female|Female||Female|Female|Female|Female|Female|Female|Female|Female|Female|Female||Female|Female|Female
|||Female|||||Female|
|||||||||||Female
|||Female|Female
||||Female||Female||||Female||
||||||Female|
||||Female|||Female|Female|
Female|||Female||Female||||
|Female|Female|Female||||||
Female|Female|Female|||||||
|Female||Female||||Female||
|||Female||Female|Female
|Female|Female||Female|||Female||Female
|Female||Female|
||Female||Female
Female||Female||
||Female|Female
||||||Female||||||||||||||||||||||
||Female||Female|||
||||||||Female||||||
Female|Female|Female|Female|Female|Female|Female
||Female|||||||Female|
|||Female||||
Female|||||Female||||Female|
|Female||Female|||
Female||Female|
Female||Female|||
||||Female|Female
|||||||||||||||||||||||||||||||Female||||||||Female|||||||||||Female||||||||||||||||||||||||||||||||||||
|||||Female|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
|||||||||||||||||||||||||||Female|||||Female||||||||||||||||Female|||||||Female|||
||||||||||Female|||||||||||||||||||||||||||||Female|||||||||
||||||||Female|||Female||
||||||||||||||||||||||||||||Female|
Female||||||||||||||||||Female||||||||||||||||||||||||||||||||Female|||||||||||||||||||||||||||||||||||||||||
||||||||||||||||||Female|||

SyntaxError: unexpected EOF while parsing (3660916054.py, line 1)